### ISSUE TITLE
Artist Not Showing Up In iTunes

### ISSUE THREAD

**Issue by lowvisiondave** [basilfx/SubDaap#2]
Love this project! I have noticed that an artist is not showing up in iTunes despite being in the Subsonic database. It doesn't seem to have made it into the database.db file locally. 

I've only noticed one band missing so far (AFI), but the total song count is also not adding up (Subsonic says 7470 and iTune only says 6903). 

Not too sure what would be causing this?

**Comment by basilfx** [comment]
Synchronization with SubSonic is still very fragile. The problem is that SubSonic has a terrible API, so there is a lot of hacking going on. I do know there is some problems with Various Artists, as they do have a name, but no artist ID, therefore they do not show up. Further more, it really depends on metadata provided by SubSonic (which comes from the files).

I am hoping to release a better synchronization soon.

**Comment by ties** [comment]
I had some issues with this as well. I wrote a dirty, dirty kludge that handles some of the songs.

I [made a pull request](https://github.com/basilfx/SubDaap/pull/3) for it but this is not the correct way to handle it. I guess the correct way is to
walk the file tree when syncing instead of searching by artist/using metadata.

**Comment by lowvisiondave** [comment]
@ties Your pull request didn't fix the problem with certain artists not showing up. I literally don't see an entire artist (9 albums) anywhere in iTunes.

The Various Artist handling is pretty cool though. I don't have many Various Artist albums but it's nice to have the artists on them sorted properly.

**Comment by ties** [comment]
@davidkeefe24: I am not sure about albums with "Various Artists" as the artist. I think the subsonic API handles these in a strange way.

This patch makes SubDaap show all songs in an album where the song's artist is not equal to the album artist. In that case, the API returns no artistID.

For example. in [this](http://en.wikipedia.org/wiki/Synesthesia_-_I_Think_in_Colours) album, all song that are "featuring  ..." have that artist in the artist field. Those are the cases that this patch fixes.

**Comment by basilfx** [comment]
@davidkeefe24 @ties Sorry for not fixing this issue earlier. I recently graduated and started working at a company, and that took/takes away my spare time :-)

Anyway, I have fixed a potential problem that could cause this issue in 32a9d501d15740d9cd6c9fb79142bde6a259b3a4. Can you check this out? Furthermore, you may want to install the latest version of [flask-daapserver](https://github.com/basilfx/flask-daapserver) from Github. It contains fixes for iTunes 12.1.

**Comment by ties** [comment]
All songs seem to be put in the database. However, I still have some songs with no artist, even though the artist info is available in subsonic.

I am re-testing my patch, rebased from `master`.

In my library there are 29 songs without an artist with this patch enabled. Without this patch, 505 songs do not have an artist.

**Comment by basilfx** [comment]
Version v2.0.0 is out, and I have fixed several issues thanks to @ties.

Please open a new issue if you think the problem is not yet solved :)
